d1<-read.csv("/home/myron/Documents/Data Mining/data1.csv")
dist1<-dist(d1)
d2<-read.csv("/home/myron/Documents/Data Mining/data2.csv")
dist1<-dist(d1)
dist2<-dist(d2)
dist_num<-as.matrix(dist2)
dist_num<-as.matrix(dist1)
library(cluster)
dist1<-daisy(d1)
dist_nom<-as.matrix(dist1)
dim1<-d1$Dessig
s1<-daisy(as.data.frame(dim1))
s1<-as.matrix(s1)
d11 = ordered(d1$Dessig, levels = c("D1","D2","D3","D4","D5"))
s1 <- daisy(as.data.frame(d11))
s1 = as.matrix(s1)
d1=d1[,-1]
dist_ordinal=as.matrix(daisy(d1))
dist_ordinal2<-as.matrix(daisy(d1,type=list(assym=2)))
View(dist_ordinal)
View(dist_ordinal2) 